//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT_Nhom_05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int MaKhuyenMai { get; set; }
        public string TenKhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<decimal> GiaTriKhuyenMai { get; set; }
        public string LoaiKhuyenMai { get; set; }
    }
}
